mongo {
  uri          = "mongodb://localhost:27017"
  uri          = ${?MONGO_URI}
  databaseName = "ev"
  databaseName = ${?MONGO_DB_NAME}
  maxPoolSize  = 10
  maxPoolSize  = ${?MONGO_MAX_POOL_SIZE}
}

pricing {
  httpPort        = 8080
  httpPort        = ${?PRICING_HTTP_PORT}
  grpcPort        = 9090
  grpcPort        = ${?PRICING_GRPC_PORT}
  defaultCurrency = "EUR"
  defaultCurrency = ${?PRICING_DEFAULT_CURRENCY}
}
