version = "3.8.3"
runner.dialect = scala3

maxColumn = 120
indent.main = 2
indent.significant = 2

align.preset = more
align.tokens."+" = [
  { code = "=", owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type))" }
  { code = "->", owner = "Term.ApplyInfix" }
  { code = "%",  owner = "Term.ApplyInfix" }
  { code = "%%", owner = "Term.ApplyInfix" }
]

newlines.source = keep
newlines.topLevelStatementBlankLines = [
  { blanks { before = 1 } }
]

rewrite.rules = [RedundantBraces, RedundantParens, SortImports, PreferCurlyFors]
rewrite.redundantBraces.stringInterpolation = true

docstrings.style = Asterisk
docstrings.wrap = no
