apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ev-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: EV Charging Platform — Scala microservices

  sourceRepos:
    - "https://github.com/itbeans/sev-platform-2.1"

  destinations:
    - namespace: ev-platform
      server: https://kubernetes.default.svc
    - namespace: ev-platform-staging
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  roles:
    - name: deploy-bot
      description: CI/CD bot — image tag updates only
      policies:
        - p, proj:ev-platform:deploy-bot, applications, sync, ev-platform/*, allow
        - p, proj:ev-platform:deploy-bot, applications, get, ev-platform/*, allow
      jwtTokens: []

  orphanedResources:
    warn: true
