apiVersion: v1
kind: Service
metadata:
  name: {{ include (print .Chart.Name ".fullname") . }}
  labels:
    {{- include (print .Chart.Name ".labels") . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.sessionAffinity (ne .Values.service.sessionAffinity "None") }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.grpcPort }}
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
    {{- if .Values.service.wsPort }}
    - port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
    {{- end }}
  selector:
    {{- include (print .Chart.Name ".selectorLabels") . | nindent 4 }}
